import os
import requests
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import status

SYSTEM_INSTRUCTION = (
    "You are a friendly, encouraging, and knowledgeable AI Financial Coach named 'InvestEd Coach' for school and college students. "
    "Your goal is to explain complex financial and investment concepts (like stocks, mutual funds, SIPs, compounding, diversification, and inflation) "
    "in a very simple, intuitive, and relatable way. Use real-world analogies (like lemonade stands, birthday cakes, trading cards, etc.). "
    "Keep your responses concise, well-formatted with markdown and lists, and use friendly emojis (like 🚀, 📈, 💰, 💡). "
    "If the user asks questions unrelated to finance, personal growth, careers, or economics, politely guide them back to financial learning."
)

MOCK_RESPONSE = (
    "👋 Hello there! I'm your **InvestEd AI Coach**. \n\n"
    "It looks like the server has not configured the `GROQ_API_KEY` environment variable yet. "
    "Once configured, I will be able to answer any question using advanced Groq intelligence! "
    "In the meantime, let me tell you that **compound interest** is when you earn interest on both your initial investment and the interest you've already accumulated. "
    "It's like rolling a small snowball down a hill—the further it goes, the bigger it gets! ❄️📈"
)

class ChatbotView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        api_key = os.environ.get('GROQ_API_KEY', '')
        
        # Get messages from request
        req_messages = request.data.get('messages', [])
        
        if not api_key:
            # Return fallback mock response if no key is configured
            return Response({
                "text": MOCK_RESPONSE
            })
            
        # Format messages for Groq API (OpenAI compatible)
        messages = [{"role": "system", "content": SYSTEM_INSTRUCTION}]
        
        for msg in req_messages:
            role = msg.get('role', 'user')
            if role in ['assistant', 'coach', 'model']:
                role = 'assistant'
            else:
                role = 'user'
                
            text = msg.get('text', '')
            if text:
                messages.append({
                    "role": role,
                    "content": text
                })
                
        # If no messages except system were constructed, return error
        if len(messages) <= 1:
            return Response({"error": "No messages provided"}, status=status.HTTP_400_BAD_REQUEST)
            
        # Call Groq API
        url = "https://api.groq.com/openai/v1/chat/completions"
        model = os.environ.get('GROQ_MODEL', 'llama-3.3-70b-versatile')
        payload = {
            "model": model,
            "messages": messages,
            "temperature": 0.7
        }
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        try:
            response = requests.post(url, json=payload, headers=headers, timeout=15)
            response.raise_for_status()
            res_data = response.json()
            
            # Extract text from response
            choices = res_data.get('choices', [])
            if choices:
                message = choices[0].get('message', {})
                text = message.get('content', '')
                if text:
                    return Response({"text": text})
            
            return Response({"error": "No text generated by AI model"}, status=status.HTTP_502_BAD_GATEWAY)
            
        except Exception as e:
            return Response({"error": f"Failed to contact Groq API: {str(e)}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
